### ISSUE TITLE
Process for New Icons

### ISSUE THREAD

**Issue by wtchappell** [mapshakers/mapkeyicons#5]
Does this project accept requests for new icons? What about contributing new icons?

I'm using these icons as part of a Minecraft map, and there are a few odds and ends that would be great to have. In particular, I'm looking for some sort of portal/magical arched gateway looking icon and an icon for a pyramid.

Regardless, I'm getting a fair amount of mileage from what's already provided - and for that I thank you!

**Comment by filipzava** [comment]
First of all, thank you for using **mapkeyicons**! The usage in a Minecraft map is very interesting. May you please provide a sample image of that? And of course, we accept requests. Do you have any ideas or sketches?

**Comment by wtchappell** [comment]
Thanks for the quick reply!

Here's a link to my servers Dynmap instance:
http://rammus.errorsuccess.net/

More markers and detail should show up as you zoom in.

Here's some information on Nether Portals, including pictures:
http://minecraft.gamepedia.com/Nether_portal

And here's some for Desert Temples - also with pictures:
http://minecraft.gamepedia.com/Desert_temple

I'm currently using the flame and basestone(?) icons for portals, and the ruined castle for pyramids/desert temples. 

For the portals, I'm thinking of an arched stone-looking gate with a swirling vortex looking thing inside. For the pyramids, I'm imagining a triangle with brick-lines. I can take a crack at trying to draw something tomorrow afternoon - I'll go ahead and apologize in advance for subjecting you to my artistic 'talents'. :)

**Comment by wtchappell** [comment]
I cannot draw, so I apologize for the terrors that I'm about to inflict on you. I'm submitting these as ideas, not as contributions in and of themselves.

![Awful Pyramid](http://i.imgur.com/y23qolR.png)

The angles should snap, the bricks should probably(?) be roughly the same size, and the mortar lines might look better thicker. It should also probably not have the hard black edge to match the others.

**Comment by wtchappell** [comment]
![Awful Portal](http://i.imgur.com/NQ2e6hU.png)

The arch should ideally be more of a perfect curve - or be made out of rougher stone chunks. The vortex in the middle should be more regular, and the lines probably proportionally a bit thicker. I dunno how easily done that is with the pixel budget on these icons - I'm entirely open to altering either idea as you see fit.

**Comment by filipzava** [comment]
Check out the new icons! I hope you will find them useful.
![pyramid](https://cloud.githubusercontent.com/assets/12759049/12950353/0d140286-d00d-11e5-8736-786677e9a4f3.png)
![magic_portal](https://cloud.githubusercontent.com/assets/12759049/12950356/0fea9858-d00d-11e5-8506-aea7fb00bf1d.png)

**Comment by wtchappell** [comment]
Requesting new icons has been a great experience - thank you!
