### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by boldtrn** [mapshakers/mapkeyicons#8]
I really like this iconset, but I currently have an issue. I want to use these icons colored, adding a color is easy, however I can only color the whole svg (tooling limitation...), so I was wondering if it would be possible to get the background transparent or to remove the background path? I tried to do this by hand, but couldn't really make it work. If I simply add a color, the results looks pretty sloppy and you cannot really see what is happening.

**Comment by filipzava** [comment]
Hi, thank you for your feedback! If I understand well, you are about to remove grey background and color icon. Actually it is very easy. There are more options and workarounds: 

- if you want to change by hand each icon, the simplest way is to open it in text editor and change the following ```style``` element to (also for coloring foreground)
```svg
<style type="text/css">
<![CDATA[
	.st0{fill:#464646;}
	.st1{fill:none;}
]]>
</style>

``` 
- or you can open svg file in some graphics vector editor (Inkscape, Adobe Illustrator), select and remove background path and color foreground path

- if you are using these icons for your web project the simplest thing is overwrite css style
```css
.st0 { 
   fill: #464646 !important; 
}

.st1 {
   fill: none !important;
}
```
-  the another option is use icons as a font

Hope this is what you are loking for.

**Comment by boldtrn** [comment]
@filipzava Thank you so much for your quick reply. Somehow my toolchain seems to mislike the mountain.svg. If I delete the background path it still colors the whole mountain svg. If I use the rocks.svg it works (after deleting the background path). Very weird. I think we can close this issue in this case, as it is no issue of the mapkeyicons.
